-- Script completo: tabelle messages, posts, comments per Memora
-- Esegui in Supabase > SQL Editor > Run

-- 1. Tabella MESSAGES (chat)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  text text not null,
  sender_name text,
  sender_id text
);

-- 2. Tabella POSTS (feed MemoraBook) – con colonne per avatar e immagini
create table if not exists posts (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  author text,
  author_id text,
  author_photo text,
  text text,
  image text,
  likes int4 default 0
);

-- 3. Tabella COMMENTS (commenti sotto i post)
create table if not exists comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  created_at timestamptz default now(),
  author_name text not null,
  author_id text,
  author_photo text,
  text text not null,
  likes int4 default 0
);

-- 4. Abilita RLS
alter table messages enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;

-- 5. Policy semplici (tutti possono leggere e scrivere) – idempotente
drop policy if exists "Allow all access to messages" on messages;
create policy "Allow all access to messages" on messages for all using (true);
drop policy if exists "Allow all access to posts" on posts;
create policy "Allow all access to posts" on posts for all using (true);
drop policy if exists "Allow all access to comments" on comments;
create policy "Allow all access to comments" on comments for all using (true);

-- Se posts esisteva già senza queste colonne, aggiungile:
alter table posts add column if not exists author_id text;
alter table posts add column if not exists author_photo text;
alter table posts add column if not exists image text;
